import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

import Navbar from "@/app/components/Navbar";
import Footer from "./components/Footer";
import SessionWrapper from "@/app/components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

        <head>
          <Script src="https://cdn.lordicon.com/lordicon.js" />
        </head>
      
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased
          bg-[linear-gradient(180deg,#6D28D9_0%,#312E81_100%)]
          text-white
          min-h-screen`}
        >
          <SessionWrapper>
            <Navbar />
          <main>{children}</main>
            <Footer />
          </SessionWrapper>
        </body>
      
    </html>
  );
}
